labels_en = ['pink primrose',
             'hard-leaved pocket orchid',
             'canterbury bells',
             'sweet pea',
             'english marigold',
             'tiger lily',
             'moon orchid',
             'bird of paradise',
             'monkshood',
             'globe thistle',
             'snapdragon',
             "colt's foot",
             'king protea',
             'spear thistle',
             'yellow iris',
             'globe-flower',
             'purple coneflower',
             'peruvian lily',
             'balloon flower',
             'giant white arum lily',
             'fire lily',
             'pincushion flower',
             'fritillary',
             'red ginger',
             'grape hyacinth',
             'corn poppy',
             'prince of wales feathers',
             'stemless gentian',
             'artichoke',
             'sweet william',
             'carnation',
             'garden phlox',
             'love in the mist',
             'mexican aster',
             'alpine sea holly',
             'ruby-lipped cattleya',
             'cape flower',
             'great masterwort',
             'siam tulip',
             'lenten rose',
             'barbeton daisy',
             'daffodil',
             'sword lily',
             'poinsettia',
             'bolero deep blue',
             'wallflower',
             'marigold',
             'buttercup',
             'oxeye daisy',
             'common dandelion',
             'petunia',
             'wild pansy',
             'primula',
             'sunflower',
             'pelargonium',
             'bishop of llandaff',
             'gaura',
             'geranium',
             'orange dahlia',
             'pink-yellow dahlia',
             'cautleya spicata',
             'japanese anemone',
             'black-eyed susan',
             'silverbush',
             'californian poppy',
             'osteospermum',
             'spring crocus',
             'bearded iris',
             'windflower',
             'tree poppy',
             'gazania',
             'azalea',
             'water lily',
             'rose',
             'thorn apple',
             'morning glory',
             'passion flower',
             'lotus',
             'toad lily',
             'anthurium',
             'frangipani',
             'clematis',
             'hibiscus',
             'columbine',
             'desert-rose',
             'tree mallow',
             'magnolia',
             'cyclamen ',
             'watercress',
             'canna lily',
             'hippeastrum ',
             'bee balm',
             'ball moss',
             'foxglove',
             'bougainvillea',
             'camellia',
             'mallow',
             'mexican petunia',
             'bromelia',
             'blanket flower',
             'trumpet creeper',
             'blackberry lily'
             ]

# labels_cn = [
# “粉色的樱草”,
# “hard-leaved口袋兰花”,
# “风铃草”,
# “香豌豆”,
# “英语万寿菊”,
# “老虎百合”,
# “月亮兰花”,
# “鸟的天堂”,labels_cn = [
# “粉色的樱草”,
# “hard-leaved口袋兰花”,
# “风铃草”,
# “香豌豆”,
# “英语万寿菊”,
# “老虎百合”,
# “月亮兰花”,
# “鸟的天堂”,
# “舟形乌头”,
# “全球蓟”,
# “金鱼草”,
# “小马的脚”,
# “山龙眼王”,
# “矛蓟”,
# 黄色的虹膜,
# “globe-flower”,
# 紫松果菊,
# 秘鲁莉莉,
# “桔梗花”,
# 巨大的白色阿鲁姆莉莉,
# “火百合”,
# “枕形花”,
# 贝母,
# “红姜”,
# “葡萄风信子”,
# “虞美人”,
# “威尔士亲王的羽毛”,
# “无梗的龙胆”,
# “洋蓟”,
# “威廉甜”,
# “康乃馨”,
# “夹竹桃花园”,
# “爱在雾中”,
# “墨西哥aster”,
# “高山海冬青”,
# “ruby-lipped洋兰’,
# “花角”,
# “伟大的masterwort”,
# “暹罗郁金香”,
# “四旬斋的玫瑰”,
# “barbeton黛西”,
# “水仙”,
# 剑兰,
# “一品红”,
# “舞深蓝”,
# “壁花”,
# 万寿菊,
# 毛茛属植物,
# “牛眼菊菊”,
# 常见的蒲公英,
# “佩妮”,
# “野生三色堇”,
# “报春花”,
# “向日葵”,
# 天竺葵属植物,
# “llandaff主教”,
# “gaura”,
# 天竺葵,
# “橙色大丽花”,
# “粉黄大丽花?”
# “cautleya spicata’,
# 日本“海葵”,
# 黑眼苏珊,
# “silverbush”,
# “加州罂粟”,
# “osteospermum”,
# “春天的番红花”,
# “大胡子虹膜”,
# “白头翁”,
# “树罂粟”,
# “原产地”,
# “杜鹃”,
# “睡莲”,
# “玫瑰”,
# “曼陀罗”,
# “牵牛花”,
# 西番莲,
# “莲花”,
# “蟾蜍莉莉”,
# 花烛属植物,
# “鸡蛋花树”,
# 铁线莲,
# “芙蓉”,
# “耧斗菜”,
# “沙漠玫瑰”,
# “锦葵树”,
# “木兰”,
# “仙客来”,
# “豆瓣菜”,
# 美人蕉莉莉,
# “hippeastrum”,
# “蜜蜂”,
# “莫斯球”,
# 毛地黄,
# 叶子花属,
# “茶花”,
# “锦葵”,
# “墨西哥佩妮”,
# “bromelia”,
# “毯子花”,
# “紫薇”,
# “射干”
# ]
